// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC7_dYaVgKaflrEfLh8wvCBrU5-1CeR9s',
    appId: '1:19100621930:web:db31ef1af7f97653223e13',
    messagingSenderId: '19100621930',
    projectId: 'instagram-clone-c9a51',
    authDomain: 'instagram-clone-c9a51.firebaseapp.com',
    storageBucket: 'instagram-clone-c9a51.firebasestorage.app',
    measurementId: 'G-40W7N04SEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7w3rfvTndLDhtwOvwLv5jMmFgcjZGZs0',
    appId: '1:19100621930:android:464a1c753e4d99ee223e13',
    messagingSenderId: '19100621930',
    projectId: 'instagram-clone-c9a51',
    storageBucket: 'instagram-clone-c9a51.firebasestorage.app',
  );
}
